[build-system]
requires = ["setuptools>=61", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ComDAS"
version = "0.1.0"
description = "DASCORE companion package that adds support for compressed DAS data"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "LGPL-3.0-or-later"}
authors = [
    {name = "Byron-Selvage", email = "bselvage@mines.edu"},
]
keywords = ["dascore", "compression", "das", "dasdae"]

dependencies = [
    "numpy>=1.24",
    "dascore>=0.1.0",
    "h5py",
    "PyWavelets",
]

[project.optional-dependencies]
dev = [
	"pytest",
	"ruff",
    "sphinx",
    "furo",
    "sphinx-autodoc-typehints",
    "myst-nb",
    "matplotlib",
    "ipykernel",
]

[tool.setuptools.packages.find]
include = ["comdas*"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[project.entry-points."dascore.fiber_io"]
COMDAS__V1 = "comdas.io.h5_container:ComdasV1"

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "W"]
ignore = []
